### ISSUE TITLE
RRT_HLP issue with Rover_RTD simulation

### ISSUE THREAD

**Issue by SamudhbhavPrabhu** [skvaskov/RTD#12]
Hi,

The run_rover_RTD_simulation script in the github repo uses a two_lane_road_static_world. I modified the script to run rover_RTD with a static_box_world, but the rover always followed a straight line trajectory. Please find the simulation images below:

P.HLP = RRT_HLP
![image](https://user-images.githubusercontent.com/60042891/90340200-7e134e80-dfc4-11ea-9b14-e57aa0958b86.png)

P.HLP is empty (so straight_line_HLP by default)
![image](https://user-images.githubusercontent.com/60042891/90340208-87042000-dfc4-11ea-9e46-c7735198b6ea.png)

For the Segway_RTD simulation, I had used RRT_HLP and it worked without any issues. I am not sure why the rover is following a straight line trajectory even for RRT_HLP.

Could you please let me know how to fix the above HLP issue (rover following straight line trajectory)? 

Thanks

**Comment by skousik** [comment]
Could you provide a minimal example of how you included the `RRT_HLP` high-level planner in your code?

Suppose `P` denotes your `planner` instance. Usually you just need to set `P.HLP = RRT_HLP()` (and include whatever options for the RRT you want as arguments to the HLP), before you pass the planner `P` into the simulator. The HLP gets called by the RTD planner instance's `create_waypoint` method, if you're using a subclass of the `generic_RTD_planner` class.

**Comment by SamudhbhavPrabhu** [comment]
Thank you for the response. Please find below a screenshot of the script.

![image](https://user-images.githubusercontent.com/60042891/90436360-7f18ae80-e09e-11ea-8a7a-a4bb35dfa853.png)

Right, that is how I included the RRT_HLP high level planner in the code. 

I tried running the simulations with different bounds:

1) bounds = [-7 7 -4 4]

![image](https://user-images.githubusercontent.com/60042891/90440219-d7eb4580-e0a4-11ea-8f75-ef43677719b3.png)

It works fine here.

2) bounds = [-20 20 -10 10]

![image](https://user-images.githubusercontent.com/60042891/90440507-56e07e00-e0a5-11ea-91be-7143919e0165.png)

Obstacle size reduced for the same bounds:

![image](https://user-images.githubusercontent.com/60042891/90440540-65c73080-e0a5-11ea-9099-1d49ed875886.png)

From the images above, it looks like the rover still follows a lane change specific behavior and there is also a limitation on the size of obstacles that it can avoid colliding with, due to it's yaw rate limitations. Please let me know if this is correct and if there is a way to fix this.

**Comment by skousik** [comment]
Alright this looks correct. If you look at the [paper (see Section 4.1)](https://arxiv.org/abs/1809.06746), the Rover can only execute lane change maneuvers using the trajectory parameterization in the FRSes available in this repository. So it makes sense that it cannot plan trajectories to track the RRT output well.

You'll have to compute new FRSes that use the Segway's trajectory parameterization, but with a rectangular footprint. You'll also need to compute new tracking error functions. I recommend closely following the [tutorial](https://github.com/skousik/RTD_tutorial).
